from tkinter import*
window = Tk()
window.geometry("600x400")
principle = Label(window,text="Principle : ").place(x = 5,y = 5)
principle_input = Entry(window,width = 15)
principle_input.place(x = 75,y = 5)
time = Label(window,text="Time : ").place(x = 5,y = 35)
time_input = Entry(window,width = 15)
time_input.place(x = 75,y = 35)
rate = Label(window,text="Rate : ").place(x = 5,y = 70)
rate_input = Entry(window,width = 15)
rate_input.place(x = 75,y = 70)
def si():
    p = int(principle_input.get())
    t = int(time_input.get())
    r = int(rate_input.get())
    simple = (p*t*r)/100
    output = "Simple Intrest : " + str(simple)
    out = Label(window,text=output).place (x = 65,y = 130)
Simle_intrest = Button(window,text="Simple Intrest",padx=3,pady=3,command=si).place(x=45,y = 100)
window.mainloop()